---
title: Acrylic India
timezone: UTC
collections:
  kids:
    title: Kids
    output: true
    permalink: "/kids/:title/"
  mens:
    title: Mens
    output: true
    permalink: "/mens/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  womens:
    title: Womens
    output: true
    permalink: "/womens/:title/"
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
- scope:
    path: ''
    type: kids
  values:
    layout: product
    permalink: "/kids/:title/"
    name: ''
    image: ''
- scope:
    path: ''
    type: mens
  values:
    layout: product
    permalink: "/mens/:title/"
    name: ''
    image: ''
- scope:
    path: ''
    type: womens
  values:
    layout: product
    permalink: "/womens/:title/"
    name: ''
    image: ''
